title: modius.io
description: Geoff Bowers â€” builder of things, mostly with code.
url: https://modius.io
baseurl: ""

author:
  name: Geoff Bowers
  email: modius@daemon.com.au
  github: modius
  twitter: modius

timezone: Australia/Sydney
permalink: /posts/:slug/

markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

collections:
  relics:
    output: true
    permalink: /relics/:slug/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "relics"
    values:
      layout: post
  - scope:
      path: "0"
    values:
      layout: zero
      sitemap: false

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Gruntfile.js
  - package.json
  - node_modules
  - Rakefile.rb
  - _templates

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
